services:
  postgres:
    image: postgres:latest
    container_name: postgres_login
    restart: always
    environment:
      POSTGRES_DB: login_nextauthdb
      POSTGRES_USER: julian
      POSTGRES_PASSWORD: julianpassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_login
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
